name: fluro
description: Flexible routing for Flutter.
version: 0.1.0
author: Posse Productions LLC
homepage: http://goposse.com

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false