name: fluro
description: The brightest, hippest, coolest router for Flutter.
version: 1.0.0
author: Posse Productions LLC <apps@goposse.com>
homepage: https://github.com/goposse/fluro

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
